### ISSUE TITLE
Module not downloaded yet

### ISSUE THREAD

**Issue by ooker777** [jiawei397/yaml_to_ts_web#1]
```
✘ [ERROR] [plugin deno] Module not downloaded yet.

An error occurred during route handling or page rendering. Error: Build failed with 1 error:
error: Module not downloaded yet.
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.51/mod.js:1601:15)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1243:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.51/mod.js:1023:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.51/mod.js:1241:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1354:14
    at https://deno.land/x/esbuild@v0.14.51/mod.js:655:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.51/mod.js:752:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.51/mod.js:621:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1880:11
    at eventLoopTick (ext:core/01_core.js:181:11) {
  errors: [
    {
      detail: Error: Module not downloaded yet.
    at loadFromCLI (https://deno.land/x/esbuild_deno_loader@0.5.2/src/native_loader.ts:56:28)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async load (https://deno.land/x/esbuild_deno_loader@0.5.2/src/native_loader.ts:18:14)    
    at async callback (https://deno.land/x/esbuild@v0.14.51/mod.js:970:28)
    at async handleRequest (https://deno.land/x/esbuild@v0.14.51/mod.js:698:30),
      id: "",
      location: null,
      notes: [],
      pluginName: "deno",       
      text: "Module not downloaded yet."
    }
  ],
  warnings: []
}
An error occurred during route handling or page rendering. Error: Build failed with 1 error:    
error: Module not downloaded yet.
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.51/mod.js:1601:15)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1243:28      
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.51/mod.js:1023:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.51/mod.js:1241:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1354:14      
    at https://deno.land/x/esbuild@v0.14.51/mod.js:655:9        
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.51/mod.js:752:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.51/mod.js:621:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1880:11      
    at eventLoopTick (ext:core/01_core.js:181:11) {
  errors: [
    {
      detail: Error: Module not downloaded yet.
    at loadFromCLI (https://deno.land/x/esbuild_deno_loader@0.5.2/src/native_loader.ts:56:28)   
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async load (https://deno.land/x/esbuild_deno_loader@0.5.2/src/native_loader.ts:18:14)    
    at async callback (https://deno.land/x/esbuild@v0.14.51/mod.js:970:28)
    at async handleRequest (https://deno.land/x/esbuild@v0.14.51/mod.js:698:30),
      id: "",
      location: null,
      notes: [],
      pluginName: "deno",       
      text: "Module not downloaded yet."
    }
  ],
  warnings: []
}
An error occurred during route handling or page rendering. Error: Build failed with 1 error:    
error: Module not downloaded yet.
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.51/mod.js:1601:15)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1243:28      
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.51/mod.js:1023:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.51/mod.js:1241:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1354:14      
    at https://deno.land/x/esbuild@v0.14.51/mod.js:655:9        
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.51/mod.js:752:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.51/mod.js:621:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1880:11      
    at eventLoopTick (ext:core/01_core.js:181:11) {
  errors: [
    {
      detail: Error: Module not downloaded yet.
    at loadFromCLI (https://deno.land/x/esbuild_deno_loader@0.5.2/src/native_loader.ts:56:28)   
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async load (https://deno.land/x/esbuild_deno_loader@0.5.2/src/native_loader.ts:18:14)    
    at async callback (https://deno.land/x/esbuild@v0.14.51/mod.js:970:28)
    at async handleRequest (https://deno.land/x/esbuild@v0.14.51/mod.js:698:30),
      id: "",
      location: null,
      notes: [],
      pluginName: "deno",       
      text: "Module not downloaded yet."
    }
  ],
  warnings: []
}
```
As the result I cannot interact with the forms. This post is relevant: https://github.com/denoland/fresh/issues/1098

**Comment by ooker777** [comment]
[Updating Fresh](https://fresh.deno.dev/docs/concepts/updating "Updating Fresh | Fresh docs") solves the problem
